### ISSUE TITLE
Replace function argument 'app center name' with env value 

### ISSUE THREAD

**Issue by roam-qa-alx** [rhys-thomas-QA/Grab-Latest-App-Center-Builds#1]
**Currently**: User provides their app name into the function `getLatestBuilds("<NAME OF YOUR APP IN APP CENTER>")`

As there's a requirement of including an .env with manual entry of data (secrets, etc), why not include the app name in there also?

APP_CENTRE_APP_NAME=My app 
(though, I'm unaware how diverse `env` values can be, though there are npm libraries to manage that)

This would allow the module `pullLatestBuilds.js` to have 1 purpose and reduce any user interaction.

**Comment by rhys-thomas-QA** [comment]
Yep I considered this but wasn't sure what the benefits were, you make a good point. I will change this now

**Comment by rhys-thomas-QA** [comment]
This has now been resolved by making the function available through an NPM package. You can use the function by passing through an environment variable or by passing the name straight through to the function, whatever the user wants to do.
